firebaseのsamplefunctionをつくった
SakikoFukuda/firebaseMobileAppSample pull request #1
Opened 2020-01-10 11:01 UTC by reisato

2020-01-10 11:03 UTC, kimidoriam requested changes
`mobile`配下消しましょう 💣

2020-01-10 11:03 UTC, mahaker commented
`mobile/.gitkeep`以外を消そう

2020-01-10 11:14 UTC, mahaker commented
`package-lock.json`もコミットしたい！

2020-01-27 09:43 UTC, reisato commented
functionsの中にはいっている `package-lock.json` とは別ですか？

2020-01-27 11:46 UTC, mahaker commented
> functionsの中にはいっている package-lock.json とは別ですか？

はいってた！それです！

2020-01-27 11:46 UTC, mahaker approved these changes
LGTM!

2020-01-28 00:54 UTC, kimidoriam approved these changes

2020-01-28 00:55 UTC, reisato commented
マージします

2020-01-28 00:55 UTC, merged